#!/bin/bash

EXE_DIR="./exe"

case "$1" in
    seq)
        EXEC="$EXE_DIR/nbody_sequential"
        ;;
    omp)
        EXEC="$EXE_DIR/nbody_openmp"
        ;;
    *)
        echo "Usage: ./run [seq|omp]"
        echo ""
        echo "seq  -> run sequential version"
        echo "omp  -> run OpenMP version"
        exit 1
        ;;
esac

echo "Running $EXEC"
echo "-----------------------------"

"$EXEC"